# Generated by Django 3.0.3 on 2020-02-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_auto_20200214_1932"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("live", "Deleted"), ("deleted", "Deleted")],
                default="live",
                max_length=10,
            ),
        ),
    ]
