# Generated by Django 3.0.3 on 2020-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_auto_20200216_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[("live", "Live"), ("deleted", "Deleted")],
                default="live",
                max_length=10,
            ),
        ),
    ]
