# Generated by Django 3.0.3 on 2020-02-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_auto_20200215_1307"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post", options={"ordering": ["-created_at"]},
        ),
    ]
