# Generated by Django 3.1.7 on 2021-08-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('deleted', 'Deleted')], default='draft', max_length=10),
        ),
    ]
