base_locale: nl
locales: [nl]

data:
  read:
    - config/locales/%{locale}.yml
  write:
    - config/locales/%{locale}.yml

search:
  paths:
    - app/
  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/models
    - app/views
  exclude:
    - app/assets/images
    - app/assets/fonts

ignore_missing:
  - 'activerecord.errors.models.*.attributes.*.{blank,invalid,too_short,too_long,confirmation,taken}'

ignore_unused:
  - 'activerecord.attributes.*'
  - 'activerecord.errors.models.*'
