version: '2.1'
services:

    postgres:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 10

    app:
        build: .
        ports:
            - "8000:8000"
        command:
            - /bin/sh
            - -ecx
            - |
                ./manage.py migrate --no-input \
                && ./manage.py createsuperuser --no-input || true \
                && ./manage.py runserver 0.0.0.0:8000
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - ./:/app
        environment:
            DDO_DEBUG: 'true'
            DDO_SECRET_KEY: thisissecret
            DDO_ALLOWED_HOSTS: "*"
            DATABASE_URL: postgres://postgres:postgres@postgres/postgres
            DJANGO_SUPERUSER_USERNAME: admin
            DJANGO_SUPERUSER_PASSWORD: admin
            DJANGO_SUPERUSER_EMAIL: admin@test.com

volumes:
    pgdata: {}
