version: '2.1'
services:

    postgres:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 10

    app:
        build:
            context: .
            args:
                # Make sure dev dependencies are installed
                - POETRY_INSTALL_ARGS=
        ports:
            - "8000:8000"
        command:
            - /bin/sh
            - -ecx
            - |
                poetry run manage migrate --no-input \
                && poetry run manage createsuperuser --no-input || true \
                && poetry run uwsgi \
                    --http :8000 \
                    --module doedensonline.core.wsgi \
                    --py-auto-reload 1 \
                    --master \
                    --lazy-apps \
                    --enable-threads \
                    --need-app \
                    --processes=1
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            - DDO_DEBUG='true'
            - DDO_SECRET_KEY=thisissecret
            - DDO_ALLOWED_HOSTS="*"
            - DDO_STATIC_ROOT=/doesntmatter
            - DDO_STATIC_URL=/static/
            - DATABASE_URL=postgres://postgres:postgres@postgres/postgres
            - DJANGO_SUPERUSER_USERNAME=admin
            - DJANGO_SUPERUSER_PASSWORD=admin
            - DJANGO_SUPERUSER_EMAIL=admin@test.com
        volumes:
            - ./doedensonline:/doedensonline/doedensonline

volumes:
    pgdata: {}
