source 'https://rubygems.org'

gem 'rails', '4.1.16'
gem 'sqlite3', '1.3.13'
gem 'mini_magick', '4.9.5'
gem 'passenger', '5.3.7'
gem 'rake', '10.5.0'
gem 'dynamic_form', '1.1.4'
gem 'jquery-rails', '3.1.5'
gem 'turbolinks', '5.2.1'
gem 'sass-rails', '4.0.5'
gem 'uglifier', '2.7.2'
gem 'execjs', '2.7.0'
gem 'rubocop', '0.41.0', require: false
gem 'parser', '2.3.3.1', require: false
gem 'i18n-tasks', '0.9.24', require: false

# Pin transitive dependencies that have since dropped Ruby 2.1 support.
gem 'concurrent-ruby', '1.0.5'
gem 'mail', '2.7.1'
gem 'thor', '1.2.2'
gem 'mini_mime', '1.1.2'
gem 'minitest', '5.11.3'
