source 'https://rubygems.org'

ruby '3.1.7'

gem 'execjs', '2.10.2'
gem 'i18n-tasks', '1.1.2', require: false
gem 'jquery-rails', '4.6.1'
# json 3 rejects the quirks_mode option that Active Support 7.0 passes.
gem 'json', '2.21.2'
gem 'kaminari', '1.2.2'
gem 'mail', '2.9.1'
gem 'mini_magick', '5.4.0'
gem 'nokogiri', '1.18.10'
gem 'puma', '8.0.2'
gem 'rails', '7.0.10'
gem 'rake', '13.4.2'
gem 'rubocop', '1.91.0', require: false
gem 'rubocop-rails', '2.38.0', require: false
gem 'sprockets', '4.4.1'
gem 'sprockets-rails', '3.5.2'
# Built from source against Alpine's SQLite (see build.sqlite3 in the
# Dockerfile) rather than from a precompiled platform gem.
gem 'sqlite3', '1.7.3', force_ruby_platform: true
gem 'turbolinks', '5.2.1'
gem 'uglifier', '4.2.1'

group :test do
  gem 'minitest', '5.27.0'
  gem 'rails-controller-testing', '1.0.5'
end
