[project]
name = "iac"
version = "0.1.0"
description = ""
authors = ["Gijs van der Voort <vandervoort.gijs@gmail.com>"]

license = {text = "MIT"}
dependencies = [
    "ansible>=8.5.0",
]
requires-python = ">=3.9"
