name: Lint

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v4

      - name: Build app image
        run: docker compose build

      - name: Run RuboCop
        run: docker compose run --rm app bundle exec rubocop
