name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev --deploy
    - name: Build container
      run: docker-compose build app
    - name: docker-compose up postgres
      run: |
          docker-compose up -d postgres
          sleep 5
    - name: Check formatting
      run: |
        ./format.sh
        git diff-index --quiet HEAD --
    - name: Run checks
      run: ./check.sh
