name: Build
on: [push]

jobs:
    python:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              working-directory: ./src
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install pipenv
                  pipenv install --dev --deploy
            - name: Build and run
              working-directory: ./src
              run: docker-compose up --build -d
            - name: Run checks
              working-directory: ./src
              run: ./check.sh

    terraform:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Terraform
              run: sudo snap install terraform
            - name: Verify Terraform manifests formatting
              working-directory: ./terraform
              run: terraform fmt -check -diff
            - name: Init Terraform project
              working-directory: ./terraform
              run: terraform init
            - name: Validate Terraform manifests
              working-directory: ./terraform
              run: terraform validate
