name: main

on:
  - pull_request

jobs:

    tf:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 0.14.7
            - name: Terraform fmt
              run: terraform fmt -check

    app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.9
            - name: Install dependencies
              working-directory: ./src
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install pipenv
                  pipenv install --dev --deploy
            - name: Build and run
              working-directory: ./src
              run: docker-compose up --build -d
            - name: Run checks
              working-directory: ./src
              run: ./check.sh
