name: pr

on:
  - pull_request

jobs:

    terraform:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 1.0.6
            - name: fmt
              run: terraform fmt -check
              working-directory: ./terraform
            - name: validate
              run: terraform validate
              working-directory: ./terraform

    app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.9
            - name: Install dependencies
              working-directory: ./src
              run: |
                  python -m pip install poetry
                  poetry install
            - name: Build and run
              working-directory: ./src
              run: docker-compose up --build -d
            - name: Run checks
              working-directory: ./src
              run: poetry run task check
