name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: docker-compose build app
    - name: Check formatting
      run: |
        ./format.sh
        git diff-index --quiet HEAD -- || echo "Changes after formatting"
    - name: Run checks
      run: ./check.sh
